version: '3'
services: 
  master:
    image: assistente:master
    ports:
      - "3000:80" 
    build: .
    command: set -a && source .env
    environment:
      - "HOST=${HOST}"
      - "PORT=${PORT}"
      - "MONGODB_USERNAME=assistente"
      - "MONGODB_PWD=${MONGODB_PWD}"
      - "MONGODB_HOST=ds231242.mlab.com"
      - "MONGODB_PORT=31242"
      - "MONGODB_DBNAME=assistente"
      - "JWT_AUDIENCE=http://api.assistente.dev.org.br"
      - "JWT_ISSUER=feathers-redelivre"
      - "OPENID_ISSUER=https://id.org.br"
      - "OPENID_REDIRECT_URL=http://api.assistente.dev.org.br/authorization"
      - "OPENID_ID=${OPENID_ID}"                                  
      - "OPENID_SECRET=${OPENID_SECRET}"
      - "TELEGRAM_USERNAME=R4dar_bot"
      - "TELEGRAM_ADMINS=${TELEGRAM_ADMINS}"
      - "TELEGRAM_TOKEN=${TELEGRAM_TOKEN}"
      - "AUTHENTICATION_SECRET=${AUTHENTICATION_SECRET}"
    docs:
    image: assistente:docs
    ports:
      - "3001:80" 
    build: 
      context: .
      dockerfile: ./Dockerfile.docs
